name: Daily Trial Management

on:
  schedule:
    # Run at 1:00 AM UTC every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  manage-trials:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run trial management
        run: npm run manage:trials
        
      - name: Notify on failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Trial management job failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }} 